name: Update Custom.xaml (Debug)

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    update-file:
        runs-on: ubuntu-latest

        steps:
            # 检出代码仓库
            - name: Check out the repository
              uses: actions/checkout@v3

            # 设置 Python 环境
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            # 安装所需的依赖
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # 运行你的 Python 脚本
            - name: Run Python script
              run: |
                  python main.py

            # 打包产物（/output 文件夹）
            - name: Archive Custom.xaml
              uses: actions/upload-artifact@v4
              with:
                  name: Output Artifact
                  path: output
